import React from 'react';
import styled from 'styled-components';

const BuyBookIconContainer = styled.div`
    background-image: url('data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjEzMCIgdmlld0JveD0iMCAwIDIwMCAxMzAiIHdpZHRoPSIyMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGcgZmlsbD0ibm9uZSI+PHBhdGggZD0ibTgwLjAzMjQyMTkgMjQuODcxMDkzOGgxMTkuOTY3NTc4MXYxMi4wMDI5Mjk2aC0xMTkuOTY3NTc4MXptLTgwLjAzMjQyMTktMjQuMjcwODk4NDloMjAwdjEyLjAwMjczNDM5aC0yMDB6bTgwLjAzMjQyMTkgNDguODA5OTYwODloMTE5Ljk2NzU3ODF2MTIuMDA4Mzk4NWgtMTE5Ljk2NzU3ODF6bTAgMjQuNTUxMTcxOWgxMTkuOTY3NTc4MXYxMi4wMDI5Mjk3aC0xMTkuOTY3NTc4MXYtMTIuMDAzMzIwM3oiIGZpbGw9IiM4YThhOGEiLz48cGF0aCBkPSJtNTQuMDIzNDM3NSA3NS4zMzk2NDg0LTE3LjMyODEyNSAzMS4wODM1OTM2LTE3LjAxNzU3ODEtMjUuNDQyMzgyNmgtMTkuNjY3NTc4MTV2MTIuMDAyMzQzN2gxMy4yNTc0MjE4NWwyNC4zNTg3ODkxIDM2LjQxNjc5NjkgMTcuMTU2ODM1OS0zMC43NzU1ODU5IDcuNTc2MTcxOSAxMS43MjM2MzI5aDEzNy42MDAxOTV2LTEyLjAwMjkyOThoLTEzMS4wNjc1Nzc4bC0xNC44NjgzNTk0LTIzLjAwNTI3MzV6IiBmaWxsPSIjNzBhODAwIi8+PC9nPjwvc3ZnPg==');
    background-position: 50% 50%;
    background-repeat: no-repeat;
    background-size: cover;
    height: 21px;
    width: 20px;
`;

export const BuyBookIcon = () => <BuyBookIconContainer />;
